apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec: 
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: catalog
  ports:
  # the port that this service should serve on
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
  